---
# External Service Configuration
# Routes for services not running in Docker on this host

http:
  routers:
    # Zigbee2MQTT on IoT server
    z2m-router:
      rule: "Host(`z2m.home.homehub.dk`)"
      service: z2m-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf
    
    # Home Assistant on dedicated VM
    ha-home-router:
      rule: "Host(`ha.home.homehub.dk`)"
      service: ha-home-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf

  services:
    # Zigbee2MQTT Service (HTTP backend on IoT server)
    z2m-service:
      loadBalancer:
        servers:
          - url: "http://10.2.10.130:8099"
    
    # Home Assistant Service (HTTP backend)
    ha-home-service:
      loadBalancer:
        servers:
          - url: "http://10.2.1.200:8123"

# http:
#   routers:
#     # Example: Proxmox Router
#     proxmox-router:
#       rule: "Host(`proxmox.example.com`)"
#       service: proxmox-service
#       priority: 10
#       entryPoints:
#         - websecure
#       tls:
#         certResolver: cloudflare
#       middlewares:
#         # Optional: Add authentication
#         # - authentik@file
#         # Optional: Add custom headers
#         # - custom-headers@file
#
#     # Example: Router for a local service (Home Assistant, etc.)
#     homeassistant-router:
#       rule: "Host(`homeassistant.example.com`)"
#       service: homeassistant-service
#       entryPoints:
#         - websecure
#       tls:
#         certResolver: cloudflare
#
#     # Example: Router with path-based routing
#     api-router:
#       rule: "Host(`example.com`) && PathPrefix(`/api`)"
#       service: api-service
#       priority: 20
#       entryPoints:
#         - websecure
#       tls:
#         certResolver: cloudflare
#       middlewares:
#         - rate-limit@file
#
#   services:
#     # Example: Proxmox Service (HTTPS backend)
#     proxmox-service:
#       loadBalancer:
#         servers:
#           - url: "https://192.168.1.100:8006"
#         serversTransport: insecure-transport
#
#     # Example: Home Assistant Service (HTTP backend)
#     homeassistant-service:
#       loadBalancer:
#         servers:
#           - url: "http://192.168.1.50:8123"
#
#     # Example: API Service with multiple backends (load balancing)
#     api-service:
#       loadBalancer:
#         servers:
#           - url: "http://192.168.1.10:8080"
#           - url: "http://192.168.1.11:8080"
#         sticky:
#           cookie:
#             name: api-sticky
#             httpOnly: true
#
# # Example: Server Transport for insecure backends (skip TLS verification)
# # Useful for services with self-signed certificates
# serversTransports:
#   insecure-transport:
#     insecureSkipVerify: true
