services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_NUM_CTX=4096
    volumes:
      - /srv/docker/ollama/data:/root/.ollama
    ports:
      - "11434:11434"
    networks: [ai]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - /srv/docker/qdrant/storage:/qdrant/storage
    ports:
      - "6333:6333"
    networks: [ai]

networks:
  ai:
    driver: bridge

