services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URLS=http://10.2.0.190:11434
      - QDRANT_URI=http://10.2.0.190:6333
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=false
      - OAUTH_PROVIDER_NAME=authentik
      - OPENID_PROVIDER_URL=https://authentik.homehub.dk/application/o/openwebui/.well-known/openid-configuration
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_SCOPES=openid email profile
      - OPENID_REDIRECT_URI=https://chat.homehub.dk/oauth/oidc/callback
    dns:
      - 10.2.1.130
    volumes:
      - /srv/docker/open-webui:/app/backend/data
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.openwebui.rule=Host(`chat.homehub.dk`)
      - traefik.http.routers.openwebui.entrypoints=websecure
      - traefik.http.routers.openwebui.tls=true
      - traefik.http.routers.openwebui.tls.certresolver=cf
      - traefik.http.services.openwebui.loadbalancer.server.port=8080

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:////app/config/litellm.db
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
    volumes:
      - /srv/docker/litellm/config:/app/config
    command: ["--config", "/app/config/config.yaml", "--port", "4000", "--detailed_debug"]
    dns:
      - 10.2.1.130
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.litellm.rule=Host(`openai.homehub.dk`)
      - traefik.http.routers.litellm.entrypoints=websecure
      - traefik.http.routers.litellm.tls=true
      - traefik.http.routers.litellm.tls.certresolver=cf
      - traefik.http.services.litellm.loadbalancer.server.port=4000

networks:
  frontend:
    external: true

