model_list:
  - model_name: qwen2.5-coder-14b
    litellm_params:
      model: ollama/qwen2.5-coder:14b
      api_base: http://ollama.homehub.dk:11434
  
  - model_name: qwen2.5-7b
    litellm_params:
      model: openai/Qwen2.5-7B-Instruct
      api_base: http://vllm.homehub.dk:8000/v1

general_settings:
  master_key: ${LITELLM_MASTER_KEY}
  database_url: "sqlite:////app/config/litellm.db"

