model_list:
  - model_name: local/ollama-qwen2.5-coder-14b
    litellm_params:
      model: "ollama/qwen2.5-coder:14b"
      api_base: "http://ollama.homehub.dk:11434"
  - model_name: local/vllm-llama3-8b
    litellm_params:
      model: "hosted_vllm/meta-llama/Meta-Llama-3-8B-Instruct"
      api_base: "http://vllm.homehub.dk:8000"
general_settings:
  telemetry: false
